name: Test Plugin

on:
  pull_request:
  push:
  schedule:
    - cron: 0 1 * * MON

jobs:
  test-plugin:
    name: Test Plugin

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set-up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: asdf-vm/actions/plugin-test@v3
        with:
          command: mn --help
